// components/text-input/text-input.tsx
import { ChangeEventHandler } from "react";

type TextInputProps = {
  id: string;
  label: string;
  value: string;
  handleOnChange: ChangeEventHandler<HTMLInputElement>;
  inputType?: string;
  className?: string;
  labelClassName?: string;
  inputClassName?: string;
};

export default function TextInput(props: TextInputProps) {
  const {
    className,
    handleOnChange,
    id,
    inputClassName,
    inputType,
    label,
    labelClassName,
    value,
  } = props;

  return (
    <div className={className}>
      <label className={labelClassName} htmlFor={id}>
        {label}
      </label>
      <input
        className={inputClassName}
        id={id}
        type={inputType || "text"}
        value={value}
        onChange={handleOnChange}
      ></input>
    </div>
  );
}

// components/text-input/text-input.vue
<template>
  <div>
    <label :htmlFor="props.id">
      {{ props.label }}
    </label>
    <input
      :id="props.id"
      :type="props.inputType || 'text'"
      :value="props.value"
      :onChange="
        (event: Event) =>
          $emit('change', (event?.target as HTMLInputElement)?.value || '')
      "
    />
  </div>
</template>

<script setup lang="ts">
const props = defineProps({
  id: {
    type: String,
    required: true,
  },
  inputType: {
    type: String,
    required: true,
  },
  label: {
    type: String,
    default: '',
  },
  value: {
    type: String,
    default: '',
  },
});
</script>
